<?php
define('ROOT', dirname(__DIR__) . DIRECTORY_SEPARATOR);
define('APP', ROOT . 'app' . DIRECTORY_SEPARATOR);
define('VIEWS', ROOT . 'Views' . DIRECTORY_SEPARATOR);
define('CONTROLLERS', ROOT . 'Controllers' . DIRECTORY_SEPARATOR);
define('CORE', ROOT . 'Core' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'classes' . DIRECTORY_SEPARATOR);
define('MODELS', ROOT . 'app' . DIRECTORY_SEPARATOR . 'Core' . DIRECTORY_SEPARATOR . 'Models' . DIRECTORY_SEPARATOR);